/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitudCompletadaRouteImport } from './routes/solicitud-completada'
import { Route as IndexRouteImport } from './routes/index'

const SolicitudCompletadaRoute = SolicitudCompletadaRouteImport.update({
  id: '/solicitud-completada',
  path: '/solicitud-completada',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/solicitud-completada': typeof SolicitudCompletadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/solicitud-completada': typeof SolicitudCompletadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/solicitud-completada': typeof SolicitudCompletadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/solicitud-completada'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/solicitud-completada'
  id: '__root__' | '/' | '/solicitud-completada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SolicitudCompletadaRoute: typeof SolicitudCompletadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitud-completada': {
      id: '/solicitud-completada'
      path: '/solicitud-completada'
      fullPath: '/solicitud-completada'
      preLoaderRoute: typeof SolicitudCompletadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SolicitudCompletadaRoute: SolicitudCompletadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
